(()=>{
const SPLASH_KEY='vora-main-splash-v14';
const $=id=>document.getElementById(id);
const sections={events:['◷','События'],tasks:['☑','Задачи'],chat:['◌','Чат'],docs:['▤','Документы'],transport:['▰','Транспорт']};
function patchBrand(){const brand=document.querySelector('.brand');if(!brand)return;brand.querySelector('b')&&(brand.querySelector('b').textContent='VORA AI');brand.querySelector('small')&&(brand.querySelector('small').textContent='VA · Virtual Assistant');brand.querySelector('.mark')&&(brand.querySelector('.mark').textContent='VA');document.title='VORA AI';const h=document.querySelector('#events h1');if(h)h.textContent='TEPA Events';const v=document.querySelector('.settings-version b');if(v)v.textContent='VORA AI';const vs=document.querySelector('.settings-version span');if(vs)vs.textContent='v14.0.0 Direct'}
function patchAvatar(){const avatar=$('avatar');if(!avatar||avatar.dataset.v14)return;avatar.dataset.v14='1';avatar.addEventListener('click',()=>{avatar.classList.add('gear-mode');setTimeout(()=>avatar.classList.remove('gear-mode'),750)})}
function ensureGlobe(){const topbar=document.querySelector('.topbar');if(!topbar||$('mapGlobe'))return;const btn=document.createElement('button');btn.id='mapGlobe';btn.className='map-globe';btn.type='button';btn.setAttribute('aria-label','Открыть карту');btn.textContent='🌐';topbar.insertBefore(btn,topbar.querySelector('.brand'));btn.addEventListener('click',openMap)}
function ensureMapScreen(){if($('map'))return;const main=document.createElement('main');main.id='map';main.className='screen hidden';main.innerHTML='<section class="panel"><div class="section-title"><div><h1>Карта</h1><p>Инновационный центр Сколково</p></div><span class="live-dot">MAP</span></div><div class="map-actions"><a href="https://www.openstreetmap.org/#map=14/55.6980/37.3600" target="_blank" rel="noopener">Открыть карту</a></div><div class="map-frame"><iframe title="Карта Сколково" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=37.3000,55.6600,37.4300,55.7400&layer=mapnik&marker=55.6980,37.3600"></iframe></div></section>';document.body.insertBefore(main,$('nav'))}
function openMap(){ensureMapScreen();['events','detail','tasks','chat','docs','transport','settings','map'].forEach(id=>$(id)?.classList.toggle('hidden',id!=='map'));document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));$('subtitle')&&($('subtitle').textContent='Карта · Сколково')}
function patchNav(){document.querySelectorAll('#nav button[data-go]').forEach(btn=>{const data=sections[btn.dataset.go];if(!data||btn.dataset.v14)return;btn.dataset.v14='1';const badge=btn.querySelector('.nav-badge')?.outerHTML||'';btn.innerHTML='<span class="sphere-nav"><span class="sphere-icon">'+data[0]+'</span><span class="sphere-label">'+data[1]+'</span></span>'+badge})}
function playCosmicSound(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),master=ctx.createGain();master.gain.value=.03;master.connect(ctx.destination);const start=ctx.currentTime+.03;[[130,0,1.2,'sine'],[195,.55,1,'triangle'],[260,1.3,1.2,'sine'],[175,2.15,1.1,'triangle'],[220,3.2,1,'sine'],[294,4.1,1.2,'triangle']].forEach(n=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=n[3];o.frequency.setValueAtTime(n[0],start+n[1]);o.frequency.exponentialRampToValueAtTime(n[0]*1.08,start+n[1]+n[2]);g.gain.setValueAtTime(.0001,start+n[1]);g.gain.linearRampToValueAtTime(.18,start+n[1]+.18);g.gain.exponentialRampToValueAtTime(.0001,start+n[1]+n[2]);o.connect(g).connect(master);o.start(start+n[1]);o.stop(start+n[1]+n[2]+.02)});setTimeout(()=>ctx.close(),7000)}catch(_){}}
function swap(core,html){const cur=core.querySelector('.v14-phase');if(cur){cur.classList.add('out');setTimeout(()=>core.innerHTML=html,420)}else core.innerHTML=html}
function showSplash({force=false,sound=false,remember=true,reload=false}={}){if(remember&&!force&&localStorage.getItem(SPLASH_KEY)==='shown')return;document.getElementById('startupSplash')?.remove();document.getElementById('voraSplashV14')?.remove();const root=document.createElement('div');root.id='voraSplashV14';root.innerHTML='<div class="v14-stars"></div><div class="v14-horizon"></div><div class="v14-line"></div><div class="v14-net"></div><div class="v14-core"></div><div class="v14-progress"><div class="bar"><span></span></div><div class="txt">Обновление... <b id="v14Pct">25%</b></div></div>';document.body.prepend(root);const core=root.querySelector('.v14-core'),net=root.querySelector('.v14-net'),pct=root.querySelector('#v14Pct');if(sound)playCosmicSound();[[0,25,'<div class="v14-phase"><div class="v14-logo"><span class="markv">V</span>VOROPAEV</div><div class="v14-sub">Digital Transport Systems</div></div>',false],[2000,75,'<div class="v14-phase"><div class="v14-drive">DRIVE<br><small>in tech</small></div></div>',true],[4000,100,'<div class="v14-phase"><div class="v14-voraai"><div class="icon"></div><div class="word">VORA AI</div><div class="caption">Operational Intelligence<br>Platform</div></div></div>',false]].forEach(p=>setTimeout(()=>{swap(core,p[2]);pct.textContent=p[1]+'%';net.classList.toggle('show',p[3])},p[0]));setTimeout(()=>{root.classList.add('hide');if(remember)localStorage.setItem(SPLASH_KEY,'shown');setTimeout(()=>{if(reload)location.reload();else root.remove()},780)},6000)}
async function updateApp(e){e?.preventDefault();e?.stopPropagation();try{if('serviceWorker'in navigator){const r=await navigator.serviceWorker.getRegistration();await r?.update()}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('voice-events-pwa-')).map(k=>caches.delete(k)))}}finally{showSplash({force:true,sound:true,remember:false,reload:true})}}
function patchUpdate(){const btn=$('updateAppButton');if(!btn||btn.dataset.v14)return;btn.dataset.v14='1';btn.addEventListener('click',updateApp,true)}
function init(){patchBrand();patchAvatar();ensureGlobe();ensureMapScreen();patchNav();patchUpdate();showSplash({sound:false,remember:true})}
document.addEventListener('DOMContentLoaded',init);setTimeout(init,500);setTimeout(init,1500);window.voraDirectV14={showSplash,playCosmicSound,openMap};
})();