(()=>{
const VERSION='v18.0.0 Water Fixes';
const $=id=>document.getElementById(id);
const labels={all:'Показать все',filled:'Заполнено',wait:'Ожидает',warning:'Внимание',danger:'Просрочено'};
function st(){return window.voiceEvents&&window.voiceEvents.getState?window.voiceEvents.getState():null}
function save(){window.voiceEvents&&window.voiceEvents.save&&window.voiceEvents.save()}
function setVersion(){document.querySelectorAll('.settings-version span').forEach(x=>x.textContent=VERSION);const s=st();if(s){s.settings.appVersion=VERSION;save()}}
function refreshLabels(){const s=st();const dateText=document.querySelector('#today')?.textContent||'Дата';if($('dateBtn'))$('dateBtn').innerHTML='<span class="filter-icon">▽</span><span id="today">'+dateText+'</span>';const status=s?.filter?.status||'all';if($('filterBtn'))$('filterBtn').innerHTML='<span class="filter-icon">▽</span><span>'+(labels[status]||'Показать все')+'</span><span id="badge"></span>'}
function ensureDateModal(){if($('v18DateModal'))return;const m=document.createElement('div');m.id='v18DateModal';m.className='date-modal hidden';m.innerHTML='<div class="date-modal-card"><h2>Выбор даты</h2><input id="v18DateInput" type="date"><div class="date-modal-actions"><button type="button" id="v18DateClear">Сбросить</button><button type="button" id="v18DateApply" class="apply-date">Применить</button></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')});$('v18DateClear').addEventListener('click',()=>applyDate(''));$('v18DateApply').addEventListener('click',()=>applyDate($('v18DateInput').value||''))}
function applyDate(value){const s=st();if(s){s.filter.date=value;save()}if($('fd'))$('fd').value=value;if($('fs'))$('fs').value=s?.filter?.status||'all';$('apply')&&$('apply').click();$('v18DateModal')&&$('v18DateModal').classList.add('hidden');setTimeout(()=>{refreshLabels();setVersion()},80)}
function openDate(){ensureDateModal();$('v18DateInput').value=st()?.filter?.date||'';$('v18DateModal').classList.remove('hidden');setTimeout(()=>$('v18DateInput')&&$('v18DateInput').focus(),80)}
document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('#dateBtn');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openDate()},true);
function ensureTaskBar(){if($('taskMediaBar'))return;const bar=document.createElement('div');bar.id='taskMediaBar';bar.className='task-media-bar';bar.innerHTML='<button class="task-mic" type="button" aria-label="Голосовая заметка">🎙</button><label aria-label="Добавить фото">📷<input id="taskPhotoQuick" type="file" accept="image/*" capture="environment" hidden></label><span class="hint">Микрофон или фото для задачи</span>';document.body.appendChild(bar);$('taskPhotoQuick').addEventListener('change',e=>{const file=e.target.files&&e.target.files[0];if(file&&$('taskPhoto')){alert('Фото выбрано. Откройте поле задачи и прикрепите его штатной кнопкой, пока подключаем прямое сохранение.')}e.target.value=''});bar.querySelector('.task-mic').addEventListener('click',()=>{const txt=$('taskText');if(txt){txt.value=txt.value||'🎙 Голосовая заметка к задаче';txt.focus()}const h=bar.querySelector('.hint');h.textContent='Добавлена голосовая заметка в текст задачи';setTimeout(()=>h.textContent='Микрофон или фото для задачи',2200)})}
function screenClass(){document.body.classList.toggle('tasks-active',!!($('tasks')&&!$('tasks').classList.contains('hidden')))}
function init(){ensureDateModal();ensureTaskBar();refreshLabels();setVersion();screenClass()}
document.addEventListener('DOMContentLoaded',init);document.addEventListener('click',()=>setTimeout(()=>{screenClass();refreshLabels();setVersion()},80),true);setInterval(()=>{screenClass();setVersion()},1000);
})();